set_property IOSTANDARD LVCMOS33 [get_ports {soc_led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {soc_led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {soc_led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {soc_led_out[0]}]
set_property PACKAGE_PIN G17 [get_ports {soc_led_out[3]}]
set_property PACKAGE_PIN G19 [get_ports {soc_led_out[2]}]
set_property PACKAGE_PIN G20 [get_ports {soc_led_out[1]}]
set_property PACKAGE_PIN G18 [get_ports {soc_led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports soc_clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports soc_key_in]
set_property IOSTANDARD LVCMOS33 [get_ports soc_rst_n_in]
set_property PACKAGE_PIN F20 [get_ports soc_rst_n_in]
set_property PACKAGE_PIN U18 [get_ports soc_clk_in]
set_property PACKAGE_PIN H20 [get_ports soc_key_in]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_clk_pll/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {reg_s11[0]} {reg_s11[1]} {reg_s11[2]} {reg_s11[3]} {reg_s11[4]} {reg_s11[5]} {reg_s11[6]} {reg_s11[7]} {reg_s11[8]} {reg_s11[9]} {reg_s11[10]} {reg_s11[11]} {reg_s11[12]} {reg_s11[13]} {reg_s11[14]} {reg_s11[15]} {reg_s11[16]} {reg_s11[17]} {reg_s11[18]} {reg_s11[19]} {reg_s11[20]} {reg_s11[21]} {reg_s11[22]} {reg_s11[23]} {reg_s11[24]} {reg_s11[25]} {reg_s11[26]} {reg_s11[27]} {reg_s11[28]} {reg_s11[29]} {reg_s11[30]} {reg_s11[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {test_case[0]} {test_case[1]} {test_case[2]} {test_case[3]} {test_case[4]} {test_case[5]} {test_case[6]} {test_case[7]} {test_case[8]} {test_case[9]} {test_case[10]} {test_case[11]} {test_case[12]} {test_case[13]} {test_case[14]} {test_case[15]} {test_case[16]} {test_case[17]} {test_case[18]} {test_case[19]} {test_case[20]} {test_case[21]} {test_case[22]} {test_case[23]} {test_case[24]} {test_case[25]} {test_case[26]} {test_case[27]} {test_case[28]} {test_case[29]} {test_case[30]} {test_case[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {reg_s10[0]} {reg_s10[1]} {reg_s10[2]} {reg_s10[3]} {reg_s10[4]} {reg_s10[5]} {reg_s10[6]} {reg_s10[7]} {reg_s10[8]} {reg_s10[9]} {reg_s10[10]} {reg_s10[11]} {reg_s10[12]} {reg_s10[13]} {reg_s10[14]} {reg_s10[15]} {reg_s10[16]} {reg_s10[17]} {reg_s10[18]} {reg_s10[19]} {reg_s10[20]} {reg_s10[21]} {reg_s10[22]} {reg_s10[23]} {reg_s10[24]} {reg_s10[25]} {reg_s10[26]} {reg_s10[27]} {reg_s10[28]} {reg_s10[29]} {reg_s10[30]} {reg_s10[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list key_debounce]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk]
