# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.cache/wt [current_project]
set_property parent.project_path F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/defines.sv
set_property file_type "Verilog Header" [get_files F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/defines.sv]
read_mem {
  F:/repositories-self/riscvsoc-contest/test_data/dat/rv32ui-p-addi.dat
  F:/repositories-self/riscvsoc-contest/test_data/dat/rv32ui-p-bne.dat
}
read_verilog -library xil_defaultlib -sv {
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/led/blink_led.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/led/breath_led.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/led/cfg_led.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/key/debounce.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/decode.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/execute.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/led/flow_led.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/id2ex.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/if2id.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/key/key_top.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/key/key_trig.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/led/led_top.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/pc_counter.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/register.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/riscv_core.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/core/rom.sv
  F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/rtl/riscv_Soc.sv
}
read_ip -quiet F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.srcs/sources_1/ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all f:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.srcs/sources_1/ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.srcs/sources_1/ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all f:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.srcs/sources_1/ip/clk_pll/clk_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.srcs/constrs_1/new/riscv_soc.xdc
set_property used_in_implementation false [get_files F:/repositories-self/riscvsoc-contest/fpga/riscv-Soc/riscv-Soc.srcs/constrs_1/new/riscv_soc.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top riscv_Soc -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_Soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_Soc_utilization_synth.rpt -pb riscv_Soc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
